#####################################
############### Setup ###############
#####################################
stages:
  - lint
  - unit_test

before_script:
  - dos2unix ./gradlew || echo "dos2unix not installed, skipping"
  - chmod +x ./gradlew

#####################################
############## Linting ##############
#####################################
lint_backend:
  stage: lint
  image: eclipse-temurin:21-jdk
  script:
    - ./gradlew checkstyleMain
  artifacts:
    paths:
      - build/reports/checkstyle/
  tags:
    - cs506

#####################################
############## Testing ##############
#####################################
unit_test_frontend:
  stage: unit_test  
  tags:
    - cs506
  image: python
  script:
    - pip install -r src/requirements.txt
    - pytest --cov=src/test.py --cov-report=xml:coverage.xml
  coverage: '/COVERAGE: ([0-9]{1,3}%)/'
  rules:
    - changes:
      - src/*.py
  artifacts:
    when: on_success
    reports:
      coverage_report: 
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 30 days
    paths:
      - results.log
      - build/reports/coverage.xml

unit_test_backend:
  stage: unit_test
  image: eclipse-temurin:21-jdk
  rules:
    - changes:
      - src/main/java/com/cs506/project3a/*
      - src/test/java/com/cs506/project3a/*
  script:
    - ./gradlew clean test
  coverage: '/COVERAGE: ([0-9]{1,3}%)/'
  tags:
    - cs506
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: build/reports/jacoco/test/jacocoTestReport.xml
    paths:
      - build/reports/tests/test/
      - build/reports/jacoco/
